INSERT INTO Category (description) VALUES ('Italian')
INSERT INTO Category (description) VALUES ('Mexican')
INSERT INTO Category (description) VALUES ('Australian')
INSERT INTO Category (description) VALUES ('Sri Lankan')
INSERT INTO Category (description) VALUES ('Indian')
INSERT INTO Category (description) VALUES ('Thai')
INSERT INTO Category (description) VALUES ('Indonisian')

INSERT INTO Unit_Of_Messure (unit_of_messure) VALUES ('teaspoon')
INSERT INTO Unit_Of_Messure (unit_of_messure) VALUES ('tablespoon')
INSERT INTO Unit_Of_Messure (unit_of_messure) VALUES ('cup')
INSERT INTO Unit_Of_Messure (unit_of_messure) VALUES ('pinch')
INSERT INTO Unit_Of_Messure (unit_of_messure) VALUES ('grams')
INSERT INTO Unit_Of_Messure (unit_of_messure) VALUES ('ounce')